# Known to build in Ubuntu 18.04
name: meshlab
version: '2020.04'
summary: MeshLab
description: |
  The open source system for processing and editing 3D triangular meshes.
  It provides a set of tools for editing, cleaning, healing, inspecting,
  rendering, texturing and converting meshes. It offers features for processing
  raw data produced by 3D digitization tools/devices and for preparing models
  for 3D printing.
icon: snap/gui/meshlab.png

grade: stable
confinement: strict

apps:
  meshlab:
    command: desktop-launch meshlab
    plugs: [home, x11, mir, opengl]
  meshlabserver:
    command: desktop-launch meshlabserver
    plugs: [home, x11, opengl]


parts:
  meshlab:
    after: [desktop-qt5]
    plugin: qmake
    qt-version: qt5
    source: https://github.com/cnr-isti-vclab/meshlab.git
    build-packages:
      - qt5-default
      - qttools5-dev-tools
      - qtscript5-dev
      - libqt5xmlpatterns5-dev
      - mesa-common-dev
      - libglu1-mesa-dev
      - lib3ds-dev
      - libglew-dev
      - libeigen3-dev 
      - libopenctm-dev 
      - libgmp-dev 
      - libqhull-dev
    build: |
      qmake src/meshlab.pro "CONFIG+= system_eigen3 system_glew system_bzip2 system_openctm system_lib3ds"
      make -j4
    install: |
      cd distrib
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -a meshlab* plugins shaders textures $SNAPCRAFT_PART_INSTALL/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/lib
      cp -a lib* $SNAPCRAFT_PART_INSTALL/lib

